### ISSUE TITLE
Image doesn't work with a reverse proxy.

### ISSUE THREAD

**Issue by rene-gomez** [jobcespedes/docker-compose-moodle#2]
Hi Team

I need work with Moodle under a reverse proxy, but the Moodle containers doesn't work with a reverse proxy.

This is my Docker compose file for the reverse proxy:

```
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/www/vhost.d:/etc/nginx/vhost.d
      - /var/www/certs:/etc/nginx/certs:ro
      - /usr/share/nginx/html
    labels:
      - com.example.nginx_proxy=true

volumes:
  nginx-proxy:


networks:
  default:
    external:
      name: nginx-proxy


```

I only add the external network into the moodle docker-compose file.
when set up the moodle's containers I never see the moodle webpage.

Best regards.
